// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio/rust_audio_recorder.dart';
import 'api/city.dart';
import 'api/simple.dart';
import 'api/terrain.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 175531572;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'iron_bird_call',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  int?
  crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetBufferSize({
    required RustAudioRecorder that,
  });

  int crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetChannels({
    required RustAudioRecorder that,
  });

  int crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetSampleRate({
    required RustAudioRecorder that,
  });

  void
  crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetBufferSize({
    required RustAudioRecorder that,
    int? bufferSize,
  });

  void crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetChannels({
    required RustAudioRecorder that,
    required int channels,
  });

  void
  crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetSampleRate({
    required RustAudioRecorder that,
    required int sampleRate,
  });

  RustAudioRecorder crateApiAudioRustAudioRecorderRustAudioRecorderNew();

  Stream<Float32List>
  crateApiAudioRustAudioRecorderRustAudioRecorderStartStream({
    required RustAudioRecorder that,
  });

  Stream<Float32List>
  crateApiAudioRustAudioRecorderRustAudioRecorderStartStreamWaveform({
    required RustAudioRecorder that,
    required BigInt bufferSize,
    required BigInt samplesPerPixel,
  });

  Future<void> crateApiAudioRustAudioRecorderRustAudioRecorderStop({
    required RustAudioRecorder that,
  });

  Future<City> crateApiCityGetKarlsruhe();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<TerrainColors> crateApiTerrainTerrainColorsDefault();

  Stream<Uint8List> crateApiTerrainTerrainStream({
    required Size imageSize,
    required TerrainColors colors,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RustAudioRecorder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RustAudioRecorder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RustAudioRecorderPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int?
  crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetBufferSize({
    required RustAudioRecorder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetBufferSizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetBufferSizeConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_auto_accessor_get__buffer_size",
        argNames: ["that"],
      );

  @override
  int crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetChannels({
    required RustAudioRecorder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetChannelsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetChannelsConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_auto_accessor_get_channels",
        argNames: ["that"],
      );

  @override
  int crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetSampleRate({
    required RustAudioRecorder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetSampleRateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetSampleRateConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_auto_accessor_get_sample_rate",
        argNames: ["that"],
      );

  @override
  void
  crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetBufferSize({
    required RustAudioRecorder that,
    int? bufferSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(bufferSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetBufferSizeConstMeta,
        argValues: [that, bufferSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetBufferSizeConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_auto_accessor_set__buffer_size",
        argNames: ["that", "bufferSize"],
      );

  @override
  void crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetChannels({
    required RustAudioRecorder that,
    required int channels,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          sse_encode_u_16(channels, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetChannelsConstMeta,
        argValues: [that, channels],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetChannelsConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_auto_accessor_set_channels",
        argNames: ["that", "channels"],
      );

  @override
  void
  crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetSampleRate({
    required RustAudioRecorder that,
    required int sampleRate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          sse_encode_u_32(sampleRate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetSampleRateConstMeta,
        argValues: [that, sampleRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetSampleRateConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_auto_accessor_set_sample_rate",
        argNames: ["that", "sampleRate"],
      );

  @override
  RustAudioRecorder crateApiAudioRustAudioRecorderRustAudioRecorderNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioRustAudioRecorderRustAudioRecorderNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderNewConstMeta =>
      const TaskConstMeta(debugName: "RustAudioRecorder_new", argNames: []);

  @override
  Stream<Float32List>
  crateApiAudioRustAudioRecorderRustAudioRecorderStartStream({
    required RustAudioRecorder that,
  }) {
    final sink = RustStreamSink<Float32List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
              that,
              serializer,
            );
            sse_encode_StreamSink_list_prim_f_32_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiAudioRustAudioRecorderRustAudioRecorderStartStreamConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderStartStreamConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_start_stream",
        argNames: ["that", "sink"],
      );

  @override
  Stream<Float32List>
  crateApiAudioRustAudioRecorderRustAudioRecorderStartStreamWaveform({
    required RustAudioRecorder that,
    required BigInt bufferSize,
    required BigInt samplesPerPixel,
  }) {
    final sink = RustStreamSink<Float32List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
              that,
              serializer,
            );
            sse_encode_usize(bufferSize, serializer);
            sse_encode_usize(samplesPerPixel, serializer);
            sse_encode_StreamSink_list_prim_f_32_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiAudioRustAudioRecorderRustAudioRecorderStartStreamWaveformConstMeta,
          argValues: [that, bufferSize, samplesPerPixel, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderStartStreamWaveformConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_start_stream_waveform",
        argNames: ["that", "bufferSize", "samplesPerPixel", "sink"],
      );

  @override
  Future<void> crateApiAudioRustAudioRecorderRustAudioRecorderStop({
    required RustAudioRecorder that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiAudioRustAudioRecorderRustAudioRecorderStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAudioRustAudioRecorderRustAudioRecorderStopConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioRecorder_stop",
        argNames: ["that"],
      );

  @override
  Future<City> crateApiCityGetKarlsruhe() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_city,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCityGetKarlsruheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCityGetKarlsruheConstMeta =>
      const TaskConstMeta(debugName: "get_karlsruhe", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<TerrainColors> crateApiTerrainTerrainColorsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_terrain_colors,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerrainTerrainColorsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerrainTerrainColorsDefaultConstMeta =>
      const TaskConstMeta(debugName: "terrain_colors_default", argNames: []);

  @override
  Stream<Uint8List> crateApiTerrainTerrainStream({
    required Size imageSize,
    required TerrainColors colors,
  }) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_size(imageSize, serializer);
            sse_encode_box_autoadd_terrain_colors(colors, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiTerrainTerrainStreamConstMeta,
          argValues: [imageSize, colors, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerrainTerrainStreamConstMeta =>
      const TaskConstMeta(
        debugName: "terrain_stream",
        argNames: ["imageSize", "colors", "sink"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RustAudioRecorder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RustAudioRecorder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustAudioRecorder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustAudioRecorder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustAudioRecorder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustAudioRecorder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Size dco_decode_box_autoadd_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_size(raw);
  }

  @protected
  TerrainColors dco_decode_box_autoadd_terrain_colors(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_terrain_colors(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  City dco_decode_city(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return City(
      name: dco_decode_String(arr[0]),
      population: dco_decode_i_32(arr[1]),
      area: dco_decode_f_32(arr[2]),
      isCapital: dco_decode_bool(arr[3]),
      districtPopulations: dco_decode_list_prim_i_32_strict(arr[4]),
      districtAreas: dco_decode_list_prim_f_32_strict(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TerrainThreshold> dco_decode_list_terrain_threshold(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_terrain_threshold).toList();
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  (int, int, int) dco_decode_record_u_8_u_8_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_u_8(arr[0]),
      dco_decode_u_8(arr[1]),
      dco_decode_u_8(arr[2]),
    );
  }

  @protected
  Size dco_decode_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Size(
      width: dco_decode_i_32(arr[0]),
      height: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  TerrainColors dco_decode_terrain_colors(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TerrainColors(
      thresholds: dco_decode_list_terrain_threshold(arr[0]),
      fallback: dco_decode_record_u_8_u_8_u_8(arr[1]),
    );
  }

  @protected
  TerrainThreshold dco_decode_terrain_threshold(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TerrainThreshold(
      threshold: dco_decode_f_64(arr[0]),
      r: dco_decode_u_8(arr[1]),
      g: dco_decode_u_8(arr[2]),
      b: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WorldEvent dco_decode_world_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return WorldEvent_TerrainGenerated(
          x: dco_decode_i_32(raw[1]),
          y: dco_decode_i_32(raw[2]),
          width: dco_decode_u_32(raw[3]),
          height: dco_decode_u_32(raw[4]),
          seed: dco_decode_u_64(raw[5]),
        );
      case 1:
        return WorldEvent_WeatherChanged(
          temperature: dco_decode_f_32(raw[1]),
          humidity: dco_decode_f_32(raw[2]),
          windSpeed: dco_decode_f_32(raw[3]),
          description: dco_decode_String(raw[4]),
        );
      case 2:
        return WorldEvent_RegionEntered(
          regionName: dco_decode_String(raw[1]),
          population: dco_decode_u_32(raw[2]),
          hostile: dco_decode_bool(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustAudioRecorder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustAudioRecorder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustAudioRecorder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustAudioRecorder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Size sse_decode_box_autoadd_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_size(deserializer));
  }

  @protected
  TerrainColors sse_decode_box_autoadd_terrain_colors(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_terrain_colors(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  City sse_decode_city(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_population = sse_decode_i_32(deserializer);
    var var_area = sse_decode_f_32(deserializer);
    var var_isCapital = sse_decode_bool(deserializer);
    var var_districtPopulations = sse_decode_list_prim_i_32_strict(
      deserializer,
    );
    var var_districtAreas = sse_decode_list_prim_f_32_strict(deserializer);
    return City(
      name: var_name,
      population: var_population,
      area: var_area,
      isCapital: var_isCapital,
      districtPopulations: var_districtPopulations,
      districtAreas: var_districtAreas,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TerrainThreshold> sse_decode_list_terrain_threshold(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TerrainThreshold>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_terrain_threshold(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int, int) sse_decode_record_u_8_u_8_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_8(deserializer);
    var var_field1 = sse_decode_u_8(deserializer);
    var var_field2 = sse_decode_u_8(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  Size sse_decode_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    return Size(width: var_width, height: var_height);
  }

  @protected
  TerrainColors sse_decode_terrain_colors(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_thresholds = sse_decode_list_terrain_threshold(deserializer);
    var var_fallback = sse_decode_record_u_8_u_8_u_8(deserializer);
    return TerrainColors(thresholds: var_thresholds, fallback: var_fallback);
  }

  @protected
  TerrainThreshold sse_decode_terrain_threshold(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threshold = sse_decode_f_64(deserializer);
    var var_r = sse_decode_u_8(deserializer);
    var var_g = sse_decode_u_8(deserializer);
    var var_b = sse_decode_u_8(deserializer);
    return TerrainThreshold(
      threshold: var_threshold,
      r: var_r,
      g: var_g,
      b: var_b,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WorldEvent sse_decode_world_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_x = sse_decode_i_32(deserializer);
        var var_y = sse_decode_i_32(deserializer);
        var var_width = sse_decode_u_32(deserializer);
        var var_height = sse_decode_u_32(deserializer);
        var var_seed = sse_decode_u_64(deserializer);
        return WorldEvent_TerrainGenerated(
          x: var_x,
          y: var_y,
          width: var_width,
          height: var_height,
          seed: var_seed,
        );
      case 1:
        var var_temperature = sse_decode_f_32(deserializer);
        var var_humidity = sse_decode_f_32(deserializer);
        var var_windSpeed = sse_decode_f_32(deserializer);
        var var_description = sse_decode_String(deserializer);
        return WorldEvent_WeatherChanged(
          temperature: var_temperature,
          humidity: var_humidity,
          windSpeed: var_windSpeed,
          description: var_description,
        );
      case 2:
        var var_regionName = sse_decode_String(deserializer);
        var var_population = sse_decode_u_32(deserializer);
        var var_hostile = sse_decode_bool(deserializer);
        return WorldEvent_RegionEntered(
          regionName: var_regionName,
          population: var_population,
          hostile: var_hostile,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    RustAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioRecorderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    RustAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioRecorderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    RustAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioRecorderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioRecorder(
    RustAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioRecorderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_size(Size self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_size(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_terrain_colors(
    TerrainColors self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terrain_colors(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_city(City self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_i_32(self.population, serializer);
    sse_encode_f_32(self.area, serializer);
    sse_encode_bool(self.isCapital, serializer);
    sse_encode_list_prim_i_32_strict(self.districtPopulations, serializer);
    sse_encode_list_prim_f_32_strict(self.districtAreas, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_terrain_threshold(
    List<TerrainThreshold> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_terrain_threshold(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_u_8_u_8_u_8(
    (int, int, int) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.$1, serializer);
    sse_encode_u_8(self.$2, serializer);
    sse_encode_u_8(self.$3, serializer);
  }

  @protected
  void sse_encode_size(Size self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
  }

  @protected
  void sse_encode_terrain_colors(TerrainColors self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_terrain_threshold(self.thresholds, serializer);
    sse_encode_record_u_8_u_8_u_8(self.fallback, serializer);
  }

  @protected
  void sse_encode_terrain_threshold(
    TerrainThreshold self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.threshold, serializer);
    sse_encode_u_8(self.r, serializer);
    sse_encode_u_8(self.g, serializer);
    sse_encode_u_8(self.b, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_world_event(WorldEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case WorldEvent_TerrainGenerated(
        x: final x,
        y: final y,
        width: final width,
        height: final height,
        seed: final seed,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_i_32(x, serializer);
        sse_encode_i_32(y, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        sse_encode_u_64(seed, serializer);
      case WorldEvent_WeatherChanged(
        temperature: final temperature,
        humidity: final humidity,
        windSpeed: final windSpeed,
        description: final description,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_f_32(temperature, serializer);
        sse_encode_f_32(humidity, serializer);
        sse_encode_f_32(windSpeed, serializer);
        sse_encode_String(description, serializer);
      case WorldEvent_RegionEntered(
        regionName: final regionName,
        population: final population,
        hostile: final hostile,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(regionName, serializer);
        sse_encode_u_32(population, serializer);
        sse_encode_bool(hostile, serializer);
    }
  }
}

@sealed
class RustAudioRecorderImpl extends RustOpaque implements RustAudioRecorder {
  // Not to be used by end users
  RustAudioRecorderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RustAudioRecorderImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RustAudioRecorder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RustAudioRecorder,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RustAudioRecorderPtr,
  );

  int? get bufferSize => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetBufferSize(
        that: this,
      );

  int get channels => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetChannels(
        that: this,
      );

  int get sampleRate => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorGetSampleRate(
        that: this,
      );

  set bufferSize(int? bufferSize) => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetBufferSize(
        that: this,
        bufferSize: bufferSize,
      );

  set channels(int channels) => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetChannels(
        that: this,
        channels: channels,
      );

  set sampleRate(int sampleRate) => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderAutoAccessorSetSampleRate(
        that: this,
        sampleRate: sampleRate,
      );

  Stream<Float32List> startStream() => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderStartStream(that: this);

  Stream<Float32List> startStreamWaveform({
    required BigInt bufferSize,
    required BigInt samplesPerPixel,
  }) => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderStartStreamWaveform(
        that: this,
        bufferSize: bufferSize,
        samplesPerPixel: samplesPerPixel,
      );

  Future<void> stop() => RustLib.instance.api
      .crateApiAudioRustAudioRecorderRustAudioRecorderStop(that: this);
}
