// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<City> getKarlsruhe() => RustLib.instance.api.crateApiCityGetKarlsruhe();

class City {
  final String name;
  final int population;
  final double area;
  final bool isCapital;
  final Int32List districtPopulations;
  final Float32List districtAreas;

  const City({
    required this.name,
    required this.population,
    required this.area,
    required this.isCapital,
    required this.districtPopulations,
    required this.districtAreas,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      population.hashCode ^
      area.hashCode ^
      isCapital.hashCode ^
      districtPopulations.hashCode ^
      districtAreas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is City &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          population == other.population &&
          area == other.area &&
          isCapital == other.isCapital &&
          districtPopulations == other.districtPopulations &&
          districtAreas == other.districtAreas;
}
