// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

@freezed
sealed class WorldEvent with _$WorldEvent {
  const WorldEvent._();

  /// A new terrain chunk was generated
  const factory WorldEvent.terrainGenerated({
    required int x,
    required int y,
    required int width,
    required int height,
    required BigInt seed,
  }) = WorldEvent_TerrainGenerated;

  /// A weather system changed
  const factory WorldEvent.weatherChanged({
    required double temperature,
    required double humidity,
    required double windSpeed,
    required String description,
  }) = WorldEvent_WeatherChanged;

  /// The player moved to a new region
  const factory WorldEvent.regionEntered({
    required String regionName,
    required int population,
    required bool hostile,
  }) = WorldEvent_RegionEntered;
}
