// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `terrain_color`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<Uint8List> terrainStream({
  required Size imageSize,
  required TerrainColors colors,
}) => RustLib.instance.api.crateApiTerrainTerrainStream(
  imageSize: imageSize,
  colors: colors,
);

class Size {
  final int width;
  final int height;

  const Size({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Size &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class TerrainColors {
  final List<TerrainThreshold> thresholds;
  final (int, int, int) fallback;

  const TerrainColors({required this.thresholds, required this.fallback});

  static Future<TerrainColors> default_() =>
      RustLib.instance.api.crateApiTerrainTerrainColorsDefault();

  @override
  int get hashCode => thresholds.hashCode ^ fallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerrainColors &&
          runtimeType == other.runtimeType &&
          thresholds == other.thresholds &&
          fallback == other.fallback;
}

class TerrainThreshold {
  final double threshold;
  final int r;
  final int g;
  final int b;

  const TerrainThreshold({
    required this.threshold,
    required this.r,
    required this.g,
    required this.b,
  });

  @override
  int get hashCode => threshold.hashCode ^ r.hashCode ^ g.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerrainThreshold &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          r == other.r &&
          g == other.g &&
          b == other.b;
}
