// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../simple.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db_to_rgba`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InferencePipeline>>
abstract class InferencePipeline implements RustOpaqueInterface {
  Size get imageSize;

  set imageSize(Size imageSize);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<InferencePipeline> newInstance({required Size imageSize}) =>
      RustLib.instance.api.crateApiAudioMelSpectrogramInferencePipelineNew(
        imageSize: imageSize,
      );

  Stream<Uint8List> start();

  Future<void> stop();
}
