// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StreamCommand`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `start`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustAudioRecorder>>
abstract class RustAudioRecorder implements RustOpaqueInterface {
  int? get bufferSize;

  int get channels;

  int get sampleRate;

  set bufferSize(int? bufferSize);

  set channels(int channels);

  set sampleRate(int sampleRate);

  factory RustAudioRecorder() =>
      RustLib.instance.api.crateApiAudioRustAudioRecorderRustAudioRecorderNew();

  Stream<Float32List> startStream();

  Stream<Float32List> startStreamWaveform({
    required BigInt bufferSize,
    required BigInt samplesPerPixel,
  });

  Future<void> stop();
}
